# Konfiguracja JWT Keycloak
server:
  port: 8080

spring:
  application:
    name: iot-agent-stream-worker

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master

stream:
  mqtt-broker-uri: ${MQTT_BROKER_URI:tcp://iot-agent-mqtt-broker:1883}
  alert-api-base-url: ${ALERT_API_BASE_URL:http://iot-agent-alert-api:8080}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
